import 'package:flutter/foundation.dart';

import '../../features/blocking/domain/blocking_state.dart';
// Generated by Pigeon (`dart run pigeon --input pigeons/blocker_api.dart`).
// Until generated, this import will be missing — run codegen after `flutter pub get`.
import 'blocker_api.g.dart';

/// Facade over the native blocking module. Translates the backend [BlockingState] into a
/// native [BlockPolicy] and applies it. Only Android implements the host API today; on other
/// platforms the calls are no-ops (the plugin returns defaults).
class AppBlocker {
  AppBlocker._(this._host);

  final AppBlockerHost _host;

  static AppBlocker create() => AppBlocker._(AppBlockerHost());

  /// Pushes the current blocking state for a goal down to the native enforcer.
  Future<void> sync(BlockingState state, String goalTitle) async {
    // Nags can apply even when apps aren't the blocking mechanism, but they only make
    // sense while the member is blocked — clear everything once unblocked.
    if (!state.isBlocked) {
      await _host.clearPolicy();
      return;
    }
    await _host.applyPolicy(BlockPolicy(
      enabled: state.blockedApps.isNotEmpty,
      packages: state.blockedApps.map((a) => a.packageName).toList(),
      targetPct: (state.targetPct * 100).round(),
      currentPct: (state.currentPct * 100).round(),
      xpRemaining: state.xpRemainingToUnblock,
      goalTitle: goalTitle,
      randomOverlayEnabled: state.randomOverlayActive,
      typingSabotageEnabled: state.typingSabotageActive,
      typingSabotageText: state.typingSabotageText ?? '',
    ));
  }

  Future<void> clear() => _host.clearPolicy();

  Future<BlockerPermissions> checkPermissions() async => BlockerPermissions(
        accessibility: await _safe(_host.hasAccessibilityPermission),
        overlay: await _safe(_host.hasOverlayPermission),
        usageAccess: await _safe(_host.hasUsageAccessPermission),
      );

  Future<void> openAccessibilitySettings() => _host.openAccessibilitySettings();
  Future<void> openOverlaySettings() => _host.openOverlaySettings();
  Future<void> openUsageAccessSettings() => _host.openUsageAccessSettings();

  Future<bool> _safe(Future<bool> Function() call) async {
    try {
      return await call();
    } catch (e) {
      debugPrint('AppBlocker permission check failed: $e');
      return false;
    }
  }
}

class BlockerPermissions {
  const BlockerPermissions({required this.accessibility, required this.overlay, required this.usageAccess});
  final bool accessibility;
  final bool overlay;
  final bool usageAccess;

  bool get allGranted => accessibility && overlay && usageAccess;
}
