// <auto-generated />
using System;
using Goal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Goal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Goal.Domain.Assignments.SprintTaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToGoalMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBacklog")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginSprintId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SnapshotDifficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("SnapshotHasChecklist")
                        .HasColumnType("boolean");

                    b.Property<int?>("SnapshotManualXp")
                        .HasColumnType("integer");

                    b.Property<int?>("SnapshotOnTimeBonusXp")
                        .HasColumnType("integer");

                    b.Property<bool>("SnapshotRequiresAttachment")
                        .HasColumnType("boolean");

                    b.Property<bool>("SnapshotRequiresImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("SnapshotRequiresText")
                        .HasColumnType("boolean");

                    b.Property<int?>("SnapshotStreakBonusXp")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotXpMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToGoalMemberId");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("SprintId", "Status");

                    b.ToTable("sprint_task_assignments", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Completions.CompletionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TaskCompletionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskCompletionId");

                    b.ToTable("completion_attachments", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Completions.CompletionChecklistState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistItemTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TaskCompletionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemTemplateId");

                    b.HasIndex("TaskCompletionId");

                    b.ToTable("completion_checklist_states", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Completions.CompletionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskCompletionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterGoalMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoterGoalMemberId");

                    b.HasIndex("TaskCompletionId", "VoterGoalMemberId")
                        .IsUnique();

                    b.ToTable("completion_votes", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Completions.TaskCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<int?>("AwardedXp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeliveredOnTime")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReviewDeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SprintTaskAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByGoalMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByGoalMemberId");

                    b.HasIndex("SprintTaskAssignmentId", "Status");

                    b.ToTable("task_completions", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentSprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("SettingsId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("SettingsId");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalBlockedApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GoalSettingsId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoalSettingsId", "PackageName")
                        .IsUnique();

                    b.ToTable("goal_blocked_apps", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("goal_invites", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GoalId", "UserId")
                        .IsUnique();

                    b.ToTable("goal_members", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseXpTargetPerSprint")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebtCarryEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("FinalTriggerDaysBefore")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalTriggerTargetPct")
                        .HasColumnType("numeric(4,3)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<int>("SprintDurationDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnblockThresholdPct")
                        .HasColumnType("numeric(4,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VoteApprovalThreshold")
                        .HasColumnType("numeric(4,3)");

                    b.Property<int>("XpScalableEasy")
                        .HasColumnType("integer");

                    b.Property<int>("XpScalableHard")
                        .HasColumnType("integer");

                    b.Property<int>("XpScalableMedium")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.ToTable("goal_settings", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Identity.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoalMemberId", "Status");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Notifications.NotificationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NextFireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoalMemberId");

                    b.HasIndex("SprintId");

                    b.HasIndex("IsActive", "NextFireAt");

                    b.ToTable("notification_schedules", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Sprints.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("Status", "EndAt");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Sprints.SprintMemberState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseTargetXp")
                        .HasColumnType("integer");

                    b.Property<int>("CarriedDebtXp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedXp")
                        .HasColumnType("integer");

                    b.Property<int>("EffectiveTargetXp")
                        .HasColumnType("integer");

                    b.Property<int?>("EndDebtXp")
                        .HasColumnType("integer");

                    b.Property<Guid>("GoalMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReachedThreshold")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnblockThresholdXp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoalMemberId");

                    b.HasIndex("SprintId", "GoalMemberId")
                        .IsUnique();

                    b.ToTable("sprint_member_states", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Sprints.XpLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCompletionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.HasIndex("GoalMemberId", "SprintId");

                    b.ToTable("xp_ledger_entries", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Tasks.ChecklistItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.ToTable("checklist_item_templates", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Tasks.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasChecklist")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManualXp")
                        .HasColumnType("integer");

                    b.Property<int?>("OnTimeBonusXp")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresText")
                        .HasColumnType("boolean");

                    b.Property<int?>("StreakBonusXp")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "IsActive");

                    b.ToTable("task_definitions", (string)null);
                });

            modelBuilder.Entity("Goal.Domain.Assignments.SprintTaskAssignment", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalMember", "AssignedToGoalMember")
                        .WithMany()
                        .HasForeignKey("AssignedToGoalMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Goal.Domain.Sprints.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Tasks.TaskDefinition", "TaskDefinition")
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToGoalMember");

                    b.Navigation("Sprint");

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Goal.Domain.Completions.CompletionAttachment", b =>
                {
                    b.HasOne("Goal.Domain.Completions.TaskCompletion", "TaskCompletion")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskCompletion");
                });

            modelBuilder.Entity("Goal.Domain.Completions.CompletionChecklistState", b =>
                {
                    b.HasOne("Goal.Domain.Tasks.ChecklistItemTemplate", "ChecklistItemTemplate")
                        .WithMany()
                        .HasForeignKey("ChecklistItemTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Completions.TaskCompletion", "TaskCompletion")
                        .WithMany("ChecklistStates")
                        .HasForeignKey("TaskCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItemTemplate");

                    b.Navigation("TaskCompletion");
                });

            modelBuilder.Entity("Goal.Domain.Completions.CompletionVote", b =>
                {
                    b.HasOne("Goal.Domain.Completions.TaskCompletion", "TaskCompletion")
                        .WithMany("Votes")
                        .HasForeignKey("TaskCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Goals.GoalMember", "VoterGoalMember")
                        .WithMany()
                        .HasForeignKey("VoterGoalMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskCompletion");

                    b.Navigation("VoterGoalMember");
                });

            modelBuilder.Entity("Goal.Domain.Completions.TaskCompletion", b =>
                {
                    b.HasOne("Goal.Domain.Assignments.SprintTaskAssignment", "SprintTaskAssignment")
                        .WithMany()
                        .HasForeignKey("SprintTaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Goals.GoalMember", "SubmittedByGoalMember")
                        .WithMany()
                        .HasForeignKey("SubmittedByGoalMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintTaskAssignment");

                    b.Navigation("SubmittedByGoalMember");
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalAggregate", b =>
                {
                    b.HasOne("Goal.Domain.Identity.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Goals.GoalSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalBlockedApp", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalSettings", "GoalSettings")
                        .WithMany("BlockedApps")
                        .HasForeignKey("GoalSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalSettings");
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalInvite", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalAggregate", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalMember", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalAggregate", "Goal")
                        .WithMany("Members")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Goal.Domain.Identity.DeviceToken", b =>
                {
                    b.HasOne("Goal.Domain.Identity.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Goal.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Goal.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Goal.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalMember", "GoalMember")
                        .WithMany()
                        .HasForeignKey("GoalMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalMember");
                });

            modelBuilder.Entity("Goal.Domain.Notifications.NotificationSchedule", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalMember", "GoalMember")
                        .WithMany()
                        .HasForeignKey("GoalMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Sprints.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalMember");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Goal.Domain.Sprints.Sprint", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalAggregate", "Goal")
                        .WithMany("Sprints")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Goal.Domain.Sprints.SprintMemberState", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalMember", "GoalMember")
                        .WithMany()
                        .HasForeignKey("GoalMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Sprints.Sprint", "Sprint")
                        .WithMany("MemberStates")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalMember");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Goal.Domain.Sprints.XpLedgerEntry", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalMember", "GoalMember")
                        .WithMany()
                        .HasForeignKey("GoalMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goal.Domain.Sprints.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalMember");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Goal.Domain.Tasks.ChecklistItemTemplate", b =>
                {
                    b.HasOne("Goal.Domain.Tasks.TaskDefinition", "TaskDefinition")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Goal.Domain.Tasks.TaskDefinition", b =>
                {
                    b.HasOne("Goal.Domain.Goals.GoalAggregate", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Goal.Domain.Completions.TaskCompletion", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChecklistStates");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalAggregate", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("Goal.Domain.Goals.GoalSettings", b =>
                {
                    b.Navigation("BlockedApps");
                });

            modelBuilder.Entity("Goal.Domain.Identity.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Goal.Domain.Sprints.Sprint", b =>
                {
                    b.Navigation("MemberStates");
                });

            modelBuilder.Entity("Goal.Domain.Tasks.TaskDefinition", b =>
                {
                    b.Navigation("ChecklistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
